/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buccialexmaze;

/**
 *
 * @author bucci.alex
 */
public class CreazionePlayerGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreazionePlayerGUI.class.getName());

    /**
     * Creates new form CreazionePlayerGUI
     */
    public CreazionePlayerGUI() {
        initComponents();
        // impostazione della gui
        this.setLocationRelativeTo(null);
        this.setTitle("Configurazione della partita");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomePlayer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbDifficolta1 = new javax.swing.JRadioButton();
        rbDifficolta2 = new javax.swing.JRadioButton();
        rbDifficolta3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnConfermaNomePlayer = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jLabel4.setText("jLabel4");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(733, 419));
        setPreferredSize(new java.awt.Dimension(733, 419));
        setSize(new java.awt.Dimension(733, 419));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 220));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome giocatore");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel6.add(jLabel2, gridBagConstraints);

        txtNomePlayer.setBackground(new java.awt.Color(51, 51, 51));
        txtNomePlayer.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(txtNomePlayer, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Livello difficoltà");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel6.add(jLabel3, gridBagConstraints);

        rbDifficolta1.setBackground(new java.awt.Color(102, 0, 0));
        rbDifficolta1.setForeground(new java.awt.Color(0, 0, 0));
        rbDifficolta1.setText("1");
        rbDifficolta1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbDifficolta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDifficolta1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel6.add(rbDifficolta1, gridBagConstraints);

        rbDifficolta2.setBackground(new java.awt.Color(102, 0, 0));
        rbDifficolta2.setForeground(new java.awt.Color(0, 0, 0));
        rbDifficolta2.setText("2");
        rbDifficolta2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbDifficolta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDifficolta2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel6.add(rbDifficolta2, gridBagConstraints);

        rbDifficolta3.setBackground(new java.awt.Color(102, 0, 0));
        rbDifficolta3.setForeground(new java.awt.Color(0, 0, 0));
        rbDifficolta3.setText("Impossibile");
        rbDifficolta3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbDifficolta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDifficolta3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        jPanel6.add(rbDifficolta3, gridBagConstraints);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero massimo mele");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel6.add(jLabel5, gridBagConstraints);

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel6.add(jTextField1, gridBagConstraints);

        jPanel2.add(jPanel6, new java.awt.GridBagConstraints());

        btnConfermaNomePlayer.setBackground(new java.awt.Color(0, 0, 0));
        btnConfermaNomePlayer.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnConfermaNomePlayer.setForeground(new java.awt.Color(255, 255, 255));
        btnConfermaNomePlayer.setText("Conferma");
        btnConfermaNomePlayer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        btnConfermaNomePlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfermaNomePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaNomePlayerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(btnConfermaNomePlayer, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * selettore difficoltà 1
     *
     * @param evt evento che avviene quando premo il bottone
     */
    private void rbDifficolta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDifficolta1ActionPerformed
        if (rbDifficolta2.isSelected()) {
            rbDifficolta2.setSelected(false);
        }
        if (rbDifficolta3.isSelected()) {
            rbDifficolta3.setSelected(false);
        }
    }//GEN-LAST:event_rbDifficolta1ActionPerformed

    /**
     * selettore difficoltà 2
     *
     * @param evt evento che avviene quando premo il bottone
     */
    private void rbDifficolta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDifficolta2ActionPerformed
        if (rbDifficolta1.isSelected()) {
            rbDifficolta1.setSelected(false);
        }
        if (rbDifficolta3.isSelected()) {
            rbDifficolta3.setSelected(false);

        }
    }//GEN-LAST:event_rbDifficolta2ActionPerformed

    /**
     * selettore difficoltà 3
     *
     * @param evt evento che avviene quando premo il bottone
     */
    private void rbDifficolta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDifficolta3ActionPerformed
        if (rbDifficolta2.isSelected()) {
            rbDifficolta2.setSelected(false);

        }
        if (rbDifficolta1.isSelected()) {
            rbDifficolta1.setSelected(false);
        }
    }//GEN-LAST:event_rbDifficolta3ActionPerformed

    /**
     * impostazione del gioco
     *
     * @param evt evento di pressione
     */
    private void btnConfermaNomePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaNomePlayerActionPerformed
        String nome = txtNomePlayer.getText();
        String nMeleStr = jTextField1.getText();

        // controllo del nome vuoto
        if (nome.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Inserisci un nome!");
            return;
        }

        // difficoltà instanziata subito ad 1 nel caso non venga selezionata
        int difficolta = 1;
        if (rbDifficolta2.isSelected()) {
            difficolta = 2;
        } else if (rbDifficolta3.isSelected()) {
            difficolta = 3;
        }

        // mele instanziate a 0 nel caso non venga inserito nessun valore
        int nMele = 0;
        try {
            nMele = Integer.parseInt(nMeleStr);
        } catch (NumberFormatException e) {
            // usa 0
        }

        GameGUI game = new GameGUI(nome, difficolta, nMele);
        game.setVisible(true);
        // chiude la finestra
        this.dispose();
    }//GEN-LAST:event_btnConfermaNomePlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreazionePlayerGUI().setVisible(true));
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfermaNomePlayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton rbDifficolta1;
    private javax.swing.JRadioButton rbDifficolta2;
    private javax.swing.JRadioButton rbDifficolta3;
    private javax.swing.JTextField txtNomePlayer;
    // End of variables declaration//GEN-END:variables
}
